feat!: Release stable v1.0.0 BREAKING CHANGE: This release introduces a full provider refactor, including breaking API changes and support for both OneAPI and Legacy authentication methods.  All previous versions (<= v0.0.12) are only compatible with the legacy Zscaler API framework and do not support OneAPI.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -41,116 +41,105 @@ env:
 
 jobs:
   publish_binary:
-    strategy:
-      fail-fast: true
-      matrix:
-        goversion:
-          - 1.23.x
-
     name: publish
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-
-      # - name: Unshallow clone for tags
-      #   run: git fetch --prune --unshallow --tags
-
+      - name: Checkout Repo
+        uses: actions/checkout@v4.1.7
       - name: Install Go
         uses: actions/setup-go@v5
         with:
-          go-version: ${{ matrix.goversion }}
-
+          go-version: ${{env.GOVERSION}}
       - name: Install pulumictl
-        uses: jaxxstorm/action-install-gh-release@v1.14.0
+        uses: jaxxstorm/action-install-gh-release@v1.12.0
         with:
           repo: pulumi/pulumictl
-
       - name: Set PreRelease Version
         run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
-
       - name: Run GoReleaser
-        uses: goreleaser/goreleaser-action@v6
+        uses: goreleaser/goreleaser-action@v5.0.0
         with:
-          args: release --clean
+          args: release --clean --timeout 60m0s
           version: '~> v2'
+      - name: Create tag
+        uses: actions/github-script@v6.4.1
+        with:
+          script: |
+            github.rest.git.createRef({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              ref: 'refs/tags/sdk/${{ github.ref_name }}',
+              sha: context.sha
+            })
+    strategy:
+      fail-fast: true
 
   publish_sdk:
     name: Publish SDKs
     runs-on: ubuntu-latest
     needs: publish_binary
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4.1.7
+      # - name: Unshallow clone for tags
+      #   run: git fetch --prune --unshallow --tags
+      - name: Install Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: ${{ env.GOVERSION }}
+      - name: Install pulumictl
+        uses: jaxxstorm/action-install-gh-release@v1.12.0
+        with:
+          repo: pulumi/pulumictl
+      - name: Install Pulumi CLI
+        uses: pulumi/actions@v4
+      - name: Setup Node
+        uses: actions/setup-node@v3.8.2
+        with:
+          node-version: ${{ env.NODEVERSION }}
+      - name: Setup DotNet
+        uses: actions/setup-dotnet@v2.1.1
+        with:
+          dotnet-version: ${{ env.DOTNETVERSION }}
+      - name: Setup Python
+        uses: actions/setup-python@v4.7.1
+        with:
+          python-version: ${{ env.PYTHONVERSION }}
+      - name: Build SDK
+        run: make build_${{ matrix.language }}
+      # - name: Check worktree clean
+      #   run: |
+      #     git update-index -q --refresh
+      #     if ! git diff-files --quiet; then
+      #         >&2 echo "error: working tree is not clean, aborting!"
+      #         git status
+      #         git diff
+      #         exit 1
+      #     fi
+      - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
+        name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@v1.8.10
+        with:
+          user: ${{ env.PYPI_USERNAME }}
+          password: ${{ env.PYPI_PASSWORD }}
+          packages_dir: ${{github.workspace}}/sdk/python/bin/dist
+      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
+        uses: JS-DevTools/npm-publish@v2.2.2
+        with:
+          access: "public"
+          token: ${{ env.NPM_TOKEN }}
+          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
+          provenance: true
+      - if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
+        name: publish nuget package
+        run: |
+          dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
+          echo "done publishing packages"
     strategy:
       fail-fast: true
       matrix:
-        dotnetversion:
-          - 6.0.120
-        goversion:
-          - 1.23.x
         language:
           - nodejs
           - python
           - dotnet
           - go
-        nodeversion:
-          - 18.x
-        pythonversion:
-          - "3.11"
-    steps:
-      - uses: actions/checkout@v4
-
-      # - name: Unshallow clone for tags
-      #   run: git fetch --prune --unshallow --tags
-
-      - uses: actions/setup-go@v5
-        with:
-          go-version: ${{ matrix.goversion }}
-
-      - name: Install pulumictl
-        uses: jaxxstorm/action-install-gh-release@v1.14.0
-        with:
-          repo: pulumi/pulumictl
-
-      - uses: pulumi/action-install-pulumi-cli@v2.0.0
-
-      - uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.nodeversion }}
-          registry-url: ${{ env.NPM_REGISTRY_URL }}
-
-      - uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: ${{ matrix.dotnetverson }}
-
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.pythonversion }}
-
-      - name: Build SDK
-        run: make build_${{ matrix.language }}
-
-      - name: Check worktree clean
-        run: |
-          git update-index -q --refresh
-          if ! git diff-files --quiet; then
-              >&2 echo "error: working tree is not clean, aborting!"
-              git status
-              git diff
-              exit 1
-          fi
-
-      - uses: pypa/gh-action-pypi-publish@release/v1
-        if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
-        with:
-          user: ${{ env.PYPI_USERNAME }}
-          password: ${{ env.PYPI_PASSWORD }}
-          packages_dir: ${{github.workspace}}/sdk/python/bin/dist
-
-      - uses: JS-DevTools/npm-publish@v1
-        if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
-        with:
-          access: "public"
-          token: ${{ env.NPM_TOKEN }}
-          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
-
-      - name: publish nuget package
-        if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
-        run: dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
